spring:

  datasource:
    url: jdbc:mysql://192.168.1.228:3306/board?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
#    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true
  mvc:
    converters:
      preferred-json-mapper: jackson

logging.level:
#  org.hibernate.SQL: trace
#  org.hibernate.type: trace
  me.hongmo: debug

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 10